version: '2'
services:
  web:
    image: gunbladesniper/project-initializer:latest
    build: .
    ports:
      - "3000:3000"
    links:
      - neo4j
  neo4j:
    image: neo4j:3.1.0
    ports:
      - "7474:7474"
      - "1337:1337"
      - "7687:7687"
    volumes:
      - /opt/data